description: "Pipeline for parsing Isovalent Hubble Network flow logs. Requires the geoip."

processors:
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- set:
    copy_from: '@timestamp'
    field: event.created
- json:
    field: message
    target_field: isovalent.hubble
- date:
    field: isovalent.hubble.time
    target_field: '@timestamp'
    formats:
    - ISO8601


- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'